// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xobtwxhwoolqbuqubxbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvYnR3eGh3b29scWJ1cXVieGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTk0NDIsImV4cCI6MjA2MTc3NTQ0Mn0.6BvgiXn-Ezf64OOtsYHIkd50TXv1b9uF51k50c-yXJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);